apiVersion: apps/v1
kind: Deployment
metadata:
  name: aprncoin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aprncoin
  template:
    metadata:
      labels:
        app: aprncoin
        version: v0.15
    spec:
      containers:
      - name: aprncoin
        image: toolboc/aprncoin
        ports:
        - containerPort: 1947
          name: aprncoin
          protocol: TCP